# Generated by Django 2.2.14 on 2020-10-07 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='filegallery',
            options={'verbose_name': 'گالری فایل ها', 'verbose_name_plural': 'گالری فایل ها'},
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'گالری تصاویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'موارد سفارش', 'verbose_name_plural': 'موارد سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='paymentlog',
            options={'verbose_name': 'گزارش پرداخت', 'verbose_name_plural': 'گزارش پرداخت ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_of_product',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parentCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category', verbose_name='دسته مادر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='filegallery',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='filegallery',
            name='file',
            field=models.FileField(upload_to='media/upload/files', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='filegallery',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام جایگزین'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='pic',
            field=models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active_comment',
            field=models.BooleanField(default=False, verbose_name='فعال کردن نظرات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'پیش نویس'), (2, 'آماده فروش'), (3, 'اتمام موجودی')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='super_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.Tag', verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='province',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='عنوان'),
        ),
    ]
