# Generated by Django 2.2.14 on 2020-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201007_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_of_download',
        ),
        migrations.RemoveField(
            model_name='product',
            name='files',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, max_length=500, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='family',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_in_stock',
            field=models.IntegerField(choices=[(1, 'موجود'), (2, 'ناموجود')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_gallery',
            field=models.ManyToManyField(blank=True, to='shop.ImageGallery', verbose_name='گالری تصاویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/product/images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_product',
            field=models.ManyToManyField(blank=True, related_name='_product_related_product_+', to='shop.Product', verbose_name='محصولات مرتبط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, max_length=100, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transportation_class',
            field=models.IntegerField(blank=True, choices=[(1, 'پست پیشتاز'), (2, 'پست سفارشی'), (3, 'تیپاکس')], null=True),
        ),
    ]
