# Generated by Django 2.2.14 on 2020-10-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201007_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_in_stock',
            field=models.IntegerField(choices=[(1, 'موجود'), (2, 'ناموجود')], default=1, verbose_name='وضعیت'),
        ),
    ]
