# Generated by Django 2.2.14 on 2020-10-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201007_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=500, verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_reply',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='Payment_status',
            field=models.IntegerField(choices=[(1, 'Initial'), (2, 'To Bank'), (3, 'From Bank'), (4, 'Error'), (5, 'پرداخت شده')], default=1, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='bank_tracking_code',
            field=models.CharField(blank=True, max_length=200, verbose_name='کد تراکنش بانکی'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_code',
            field=models.CharField(max_length=200, unique=True, verbose_name='کد پرداخت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transportation_class',
            field=models.IntegerField(blank=True, choices=[(1, 'پست پیشتاز'), (2, 'پست سفارشی'), (3, 'تیپاکس')], null=True, verbose_name='نوع ارسال'),
        ),
    ]
