# Generated by Django 2.2.14 on 2020-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201007_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decsription',
            field=models.CharField(blank=True, max_length=300, verbose_name='مختصر توضیحات'),
        ),
    ]
