# Generated by Django 2.2.14 on 2020-10-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_decsription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decsription',
            field=models.CharField(max_length=300, verbose_name='مختصر توضیحات'),
        ),
    ]
