# Generated by Django 2.2.14 on 2020-10-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201011_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان فروشگاه')),
                ('descriptions', models.CharField(max_length=500, verbose_name='درباره فروشگاه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('products', models.ManyToManyField(to='shop.Product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه ها',
            },
        ),
    ]
