# Generated by Django 2.2.14 on 2020-10-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_name',
            name='products',
            field=models.ManyToManyField(null=True, to='shop.Product', verbose_name='محصولات'),
        ),
    ]
