# Generated by Django 2.2.14 on 2020-11-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_category1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_name',
            name='products',
            field=models.ManyToManyField(to='shop.Product', verbose_name='محصولات'),
        ),
    ]
