# Generated by Django 2.2.14 on 2020-11-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20201105_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parentCategory',
            new_name='child',
        ),
    ]
