# Generated by Django 2.2.14 on 2020-11-07 13:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20201107_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category1',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category1',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.Category1'),
        ),
        migrations.AlterField(
            model_name='category1',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='category1',
            unique_together={('parent', 'slug')},
        ),
    ]
