# Generated by Django 2.2.14 on 2020-11-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20201107_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category1',
            new_name='daste',
        ),
    ]
