# Generated by Django 2.2.14 on 2020-11-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20201107_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcat',
        ),
    ]
