# Generated by Django 2.2.14 on 2020-11-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_subcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='child',
            field=models.ManyToManyField(to='shop.subcat', verbose_name=''),
        ),
    ]
