# Generated by Django 2.2.14 on 2020-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
        ('shop', '0033_remove_category_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorize this item.', null=True, to='category.Category'),
        ),
    ]
