# Generated by Django 2.2.14 on 2020-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorize this item.', to='category.Category'),
        ),
    ]
