# Generated by Django 2.2.14 on 2020-11-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20201109_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subcat',
        ),
    ]
