# Generated by Django 2.2.14 on 2020-11-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_delete_subcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
