# Generated by Django 2.2.14 on 2020-11-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.Category', verbose_name='دسته بندی'),
        ),
    ]
