# Generated by Django 2.2.14 on 2020-11-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='update_at',
        ),
    ]
