# Generated by Django 2.2.14 on 2020-11-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20201117_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.City', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'منطقه ها',
            },
        ),
    ]
