# Generated by Django 2.2.14 on 2020-11-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20201118_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
    ]
