# Generated by Django 2.2.14 on 2020-12-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_orderitem_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.OrderItem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_name', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'حسابداری',
                'verbose_name_plural': 'حسابداری',
            },
        ),
    ]
