# Generated by Django 2.2.14 on 2020-12-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='checkout',
            field=models.BooleanField(null=True),
        ),
    ]
