# Generated by Django 2.2.14 on 2020-12-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_accounting_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='ammount',
            field=models.IntegerField(null=True),
        ),
    ]
