# Generated by Django 2.2.14 on 2021-01-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='pic',
            field=models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/images', verbose_name='تصویر'),
        ),
    ]
