# Generated by Django 2.2.14 on 2021-01-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_slider_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('link', models.CharField(max_length=100, unique=True, verbose_name='لینک')),
                ('pic', models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/images', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
    ]
